image: python

stages:
- test

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install tox coverage

commonroad_io_python36:
  image: python:3.6
  stage: test
  script: pip install -e .[tests] && coverage run commonroad/tests/run_tests.py
