# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commonroad/common/pb_scripts/dynamic/traffic_sign_value.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from commonroad.common.pb_scripts.common import traffic_sign_element_pb2 as commonroad_dot_common_dot_pb__scripts_dot_common_dot_traffic__sign__element__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='commonroad/common/pb_scripts/dynamic/traffic_sign_value.proto',
  package='commonroad_dynamic',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n=commonroad/common/pb_scripts/dynamic/traffic_sign_value.proto\x12\x12\x63ommonroad_dynamic\x1a>commonroad/common/pb_scripts/common/traffic_sign_element.proto\"q\n\x10TrafficSignValue\x12\x17\n\x0ftraffic_sign_id\x18\x01 \x02(\r\x12\x44\n\x15traffic_sign_elements\x18\x02 \x03(\x0b\x32%.commonroad_common.TrafficSignElement'
  ,
  dependencies=[commonroad_dot_common_dot_pb__scripts_dot_common_dot_traffic__sign__element__pb2.DESCRIPTOR,])




_TRAFFICSIGNVALUE = _descriptor.Descriptor(
  name='TrafficSignValue',
  full_name='commonroad_dynamic.TrafficSignValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='traffic_sign_id', full_name='commonroad_dynamic.TrafficSignValue.traffic_sign_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traffic_sign_elements', full_name='commonroad_dynamic.TrafficSignValue.traffic_sign_elements', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=262,
)

_TRAFFICSIGNVALUE.fields_by_name['traffic_sign_elements'].message_type = commonroad_dot_common_dot_pb__scripts_dot_common_dot_traffic__sign__element__pb2._TRAFFICSIGNELEMENT
DESCRIPTOR.message_types_by_name['TrafficSignValue'] = _TRAFFICSIGNVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrafficSignValue = _reflection.GeneratedProtocolMessageType('TrafficSignValue', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICSIGNVALUE,
  '__module__' : 'commonroad.common.pb_scripts.dynamic.traffic_sign_value_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_dynamic.TrafficSignValue)
  })
_sym_db.RegisterMessage(TrafficSignValue)


# @@protoc_insertion_point(module_scope)
