# paths can be either relative or absolute

# input directory of your intended CommonRoad scenarios
input_path: ../scenarios/
# output directory of CommonRoad solution files
output_path: ../solutions/
# overwrite solution file if it already exists
overwrite: True
# timeout time for motion planner [s]
timeout: 60

# name of the function which calls the motion planner
motion_planner_path: ../target/
motion_planner_module_name: batch_search
motion_planner_function_name: execute_search_batch

# benchmark evaluation parameters
# change 'defult' to scenario id to specify exclusive parameters for that scenario
# e.g. change 'default' to 'USA_US101-6_2_T-1'
default:
  # vehicle model, e.g., kinematic single-track model
  vehicle_model: KS
  # vehicle type, e.g, BMW 320i
  vehicle_type: BMW_320i
  # cost function
  cost_function: SM1
  # used to specify id of planner. in this example, we have
  # 1 = Greedy Best First Search, 2 = A*, else = Your own planner
  planner_id: 1
  # planner problem index. for cooperative scenarios: 0, 1, 2, ..., otherwise: 0
  planning_problem_idx: 0
  # maximum permissible depth of the search tree
  max_tree_depth: 100
