# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynamic/commonroad_dynamic.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import util_pb2 as util__pb2
import environment_pb2 as environment__pb2
import traffic_sign_value_pb2 as traffic__sign__value__pb2
import traffic_light_cycle_pb2 as traffic__light__cycle__pb2
import static_obstacle_pb2 as static__obstacle__pb2
import dynamic_obstacle_pb2 as dynamic__obstacle__pb2
import environment_obstacle_pb2 as environment__obstacle__pb2
import phantom_obstacle_pb2 as phantom__obstacle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dynamic/commonroad_dynamic.proto',
  package='commonroad_dynamic',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n dynamic/commonroad_dynamic.proto\x12\x12\x63ommonroad_dynamic\x1a\nutil.proto\x1a\x11\x65nvironment.proto\x1a\x18traffic_sign_value.proto\x1a\x19traffic_light_cycle.proto\x1a\x15static_obstacle.proto\x1a\x16\x64ynamic_obstacle.proto\x1a\x1a\x65nvironment_obstacle.proto\x1a\x16phantom_obstacle.proto\"\xaf\x01\n\x13ScenarioInformation\x12\x1b\n\x13\x63ommon_road_version\x18\x01 \x02(\t\x12\x14\n\x0c\x62\x65nchmark_id\x18\x02 \x02(\t\x12\x18\n\x04\x64\x61te\x18\x03 \x02(\x0b\x32\n.TimeStamp\x12\x0e\n\x06\x61uthor\x18\x04 \x02(\t\x12\x13\n\x0b\x61\x66\x66iliation\x18\x05 \x02(\t\x12\x0e\n\x06source\x18\x06 \x02(\t\x12\x16\n\x0etime_step_size\x18\x07 \x02(\x01\"\x8c\x04\n\nCommonRoad\x12<\n\x0binformation\x18\x01 \x02(\x0b\x32\'.commonroad_dynamic.ScenarioInformation\x12\x34\n\x0b\x65nvironment\x18\x02 \x02(\x0b\x32\x1f.commonroad_dynamic.Environment\x12\x42\n\x13traffic_light_cycle\x18\x03 \x03(\x0b\x32%.commonroad_dynamic.TrafficLightCycle\x12@\n\x12traffic_sign_value\x18\x04 \x03(\x0b\x32$.commonroad_dynamic.TrafficSignValue\x12<\n\x10static_obstacles\x18\x05 \x03(\x0b\x32\".commonroad_dynamic.StaticObstacle\x12>\n\x11\x64ynamic_obstacles\x18\x06 \x03(\x0b\x32#.commonroad_dynamic.DynamicObstacle\x12\x46\n\x15\x65nvironment_obstacles\x18\x07 \x03(\x0b\x32\'.commonroad_dynamic.EnvironmentObstacle\x12>\n\x11phantom_obstacles\x18\x08 \x03(\x0b\x32#.commonroad_dynamic.PhantomObstacle'
  ,
  dependencies=[util__pb2.DESCRIPTOR,environment__pb2.DESCRIPTOR,traffic__sign__value__pb2.DESCRIPTOR,traffic__light__cycle__pb2.DESCRIPTOR,static__obstacle__pb2.DESCRIPTOR,dynamic__obstacle__pb2.DESCRIPTOR,environment__obstacle__pb2.DESCRIPTOR,phantom__obstacle__pb2.DESCRIPTOR,])




_SCENARIOINFORMATION = _descriptor.Descriptor(
  name='ScenarioInformation',
  full_name='commonroad_dynamic.ScenarioInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_road_version', full_name='commonroad_dynamic.ScenarioInformation.common_road_version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='benchmark_id', full_name='commonroad_dynamic.ScenarioInformation.benchmark_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='commonroad_dynamic.ScenarioInformation.date', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='commonroad_dynamic.ScenarioInformation.author', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='affiliation', full_name='commonroad_dynamic.ScenarioInformation.affiliation', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='commonroad_dynamic.ScenarioInformation.source', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_step_size', full_name='commonroad_dynamic.ScenarioInformation.time_step_size', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=415,
)


_COMMONROAD = _descriptor.Descriptor(
  name='CommonRoad',
  full_name='commonroad_dynamic.CommonRoad',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='information', full_name='commonroad_dynamic.CommonRoad.information', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='environment', full_name='commonroad_dynamic.CommonRoad.environment', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traffic_light_cycle', full_name='commonroad_dynamic.CommonRoad.traffic_light_cycle', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traffic_sign_value', full_name='commonroad_dynamic.CommonRoad.traffic_sign_value', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='static_obstacles', full_name='commonroad_dynamic.CommonRoad.static_obstacles', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dynamic_obstacles', full_name='commonroad_dynamic.CommonRoad.dynamic_obstacles', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='environment_obstacles', full_name='commonroad_dynamic.CommonRoad.environment_obstacles', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phantom_obstacles', full_name='commonroad_dynamic.CommonRoad.phantom_obstacles', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=942,
)

_SCENARIOINFORMATION.fields_by_name['date'].message_type = util__pb2._TIMESTAMP
_COMMONROAD.fields_by_name['information'].message_type = _SCENARIOINFORMATION
_COMMONROAD.fields_by_name['environment'].message_type = environment__pb2._ENVIRONMENT
_COMMONROAD.fields_by_name['traffic_light_cycle'].message_type = traffic__light__cycle__pb2._TRAFFICLIGHTCYCLE
_COMMONROAD.fields_by_name['traffic_sign_value'].message_type = traffic__sign__value__pb2._TRAFFICSIGNVALUE
_COMMONROAD.fields_by_name['static_obstacles'].message_type = static__obstacle__pb2._STATICOBSTACLE
_COMMONROAD.fields_by_name['dynamic_obstacles'].message_type = dynamic__obstacle__pb2._DYNAMICOBSTACLE
_COMMONROAD.fields_by_name['environment_obstacles'].message_type = environment__obstacle__pb2._ENVIRONMENTOBSTACLE
_COMMONROAD.fields_by_name['phantom_obstacles'].message_type = phantom__obstacle__pb2._PHANTOMOBSTACLE
DESCRIPTOR.message_types_by_name['ScenarioInformation'] = _SCENARIOINFORMATION
DESCRIPTOR.message_types_by_name['CommonRoad'] = _COMMONROAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScenarioInformation = _reflection.GeneratedProtocolMessageType('ScenarioInformation', (_message.Message,), {
  'DESCRIPTOR' : _SCENARIOINFORMATION,
  '__module__' : 'dynamic.commonroad_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_dynamic.ScenarioInformation)
  })
_sym_db.RegisterMessage(ScenarioInformation)

CommonRoad = _reflection.GeneratedProtocolMessageType('CommonRoad', (_message.Message,), {
  'DESCRIPTOR' : _COMMONROAD,
  '__module__' : 'dynamic.commonroad_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_dynamic.CommonRoad)
  })
_sym_db.RegisterMessage(CommonRoad)


# @@protoc_insertion_point(module_scope)
