# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scenario_meta_information.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commonroad.common.pb_scripts.common.util_pb2 as util__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scenario_meta_information.proto',
  package='commonroad_common',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fscenario_meta_information.proto\x12\x11\x63ommonroad_common\x1a\nutil.proto\"\xf1\x01\n\x17ScenarioMetaInformation\x12\x1b\n\x13\x63ommon_road_version\x18\x01 \x02(\t\x12\x14\n\x0c\x62\x65nchmark_id\x18\x02 \x02(\t\x12\x14\n\x0clicense_name\x18\x03 \x02(\t\x12\x14\n\x0clicense_text\x18\x04 \x01(\t\x12*\n\x04\x64\x61te\x18\x05 \x02(\x0b\x32\x1c.commonroad_common.TimeStamp\x12\x0e\n\x06\x61uthor\x18\x06 \x02(\t\x12\x13\n\x0b\x61\x66\x66iliation\x18\x07 \x02(\t\x12\x0e\n\x06source\x18\x08 \x02(\t\x12\x16\n\x0etime_step_size\x18\t \x02(\x01'
  ,
  dependencies=[util__pb2.DESCRIPTOR,])




_SCENARIOMETAINFORMATION = _descriptor.Descriptor(
  name='ScenarioMetaInformation',
  full_name='commonroad_common.ScenarioMetaInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_road_version', full_name='commonroad_common.ScenarioMetaInformation.common_road_version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='benchmark_id', full_name='commonroad_common.ScenarioMetaInformation.benchmark_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='license_name', full_name='commonroad_common.ScenarioMetaInformation.license_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='license_text', full_name='commonroad_common.ScenarioMetaInformation.license_text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='commonroad_common.ScenarioMetaInformation.date', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='commonroad_common.ScenarioMetaInformation.author', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='affiliation', full_name='commonroad_common.ScenarioMetaInformation.affiliation', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='commonroad_common.ScenarioMetaInformation.source', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_step_size', full_name='commonroad_common.ScenarioMetaInformation.time_step_size', index=8,
      number=9, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=308,
)

_SCENARIOMETAINFORMATION.fields_by_name['date'].message_type = util__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ScenarioMetaInformation'] = _SCENARIOMETAINFORMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScenarioMetaInformation = _reflection.GeneratedProtocolMessageType('ScenarioMetaInformation', (_message.Message,), {
  'DESCRIPTOR' : _SCENARIOMETAINFORMATION,
  '__module__' : 'scenario_meta_information_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_common.ScenarioMetaInformation)
  })
_sym_db.RegisterMessage(ScenarioMetaInformation)


# @@protoc_insertion_point(module_scope)
