# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map/commonroad_map.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import util_pb2 as util__pb2
import location_pb2 as location__pb2
import lanelet_pb2 as lanelet__pb2
import traffic_sign_pb2 as traffic__sign__pb2
import traffic_light_pb2 as traffic__light__pb2
import intersection_pb2 as intersection__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='map/commonroad_map.proto',
  package='commonroad_map',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18map/commonroad_map.proto\x12\x0e\x63ommonroad_map\x1a\nutil.proto\x1a\x0elocation.proto\x1a\rlanelet.proto\x1a\x12traffic_sign.proto\x1a\x13traffic_light.proto\x1a\x12intersection.proto\"\xa4\x01\n\x0eMapInformation\x12\x1b\n\x13\x63ommon_road_version\x18\x01 \x02(\t\x12\x0e\n\x06map_id\x18\x02 \x02(\t\x12\x18\n\x04\x64\x61te\x18\x03 \x02(\x0b\x32\n.TimeStamp\x12\x0e\n\x06\x61uthor\x18\x04 \x02(\t\x12\x13\n\x0b\x61\x66\x66iliation\x18\x05 \x02(\t\x12\x0e\n\x06source\x18\x06 \x02(\t\x12\x16\n\x0etime_step_size\x18\x07 \x02(\x01\"\xba\x02\n\rCommonRoadMap\x12\x33\n\x0binformation\x18\x01 \x02(\x0b\x32\x1e.commonroad_map.MapInformation\x12*\n\x08location\x18\x02 \x02(\x0b\x32\x18.commonroad_map.Location\x12)\n\x08lanelets\x18\x03 \x03(\x0b\x32\x17.commonroad_map.Lanelet\x12\x32\n\rtraffic_signs\x18\x04 \x03(\x0b\x32\x1b.commonroad_map.TrafficSign\x12\x34\n\x0etraffic_lights\x18\x05 \x03(\x0b\x32\x1c.commonroad_map.TrafficLight\x12\x33\n\rintersections\x18\x06 \x03(\x0b\x32\x1c.commonroad_map.Intersection'
  ,
  dependencies=[util__pb2.DESCRIPTOR,location__pb2.DESCRIPTOR,lanelet__pb2.DESCRIPTOR,traffic__sign__pb2.DESCRIPTOR,traffic__light__pb2.DESCRIPTOR,intersection__pb2.DESCRIPTOR,])




_MAPINFORMATION = _descriptor.Descriptor(
  name='MapInformation',
  full_name='commonroad_map.MapInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_road_version', full_name='commonroad_map.MapInformation.common_road_version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map_id', full_name='commonroad_map.MapInformation.map_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='commonroad_map.MapInformation.date', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='commonroad_map.MapInformation.author', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='affiliation', full_name='commonroad_map.MapInformation.affiliation', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='commonroad_map.MapInformation.source', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_step_size', full_name='commonroad_map.MapInformation.time_step_size', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=313,
)


_COMMONROADMAP = _descriptor.Descriptor(
  name='CommonRoadMap',
  full_name='commonroad_map.CommonRoadMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='information', full_name='commonroad_map.CommonRoadMap.information', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='commonroad_map.CommonRoadMap.location', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lanelets', full_name='commonroad_map.CommonRoadMap.lanelets', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traffic_signs', full_name='commonroad_map.CommonRoadMap.traffic_signs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='traffic_lights', full_name='commonroad_map.CommonRoadMap.traffic_lights', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intersections', full_name='commonroad_map.CommonRoadMap.intersections', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=630,
)

_MAPINFORMATION.fields_by_name['date'].message_type = util__pb2._TIMESTAMP
_COMMONROADMAP.fields_by_name['information'].message_type = _MAPINFORMATION
_COMMONROADMAP.fields_by_name['location'].message_type = location__pb2._LOCATION
_COMMONROADMAP.fields_by_name['lanelets'].message_type = lanelet__pb2._LANELET
_COMMONROADMAP.fields_by_name['traffic_signs'].message_type = traffic__sign__pb2._TRAFFICSIGN
_COMMONROADMAP.fields_by_name['traffic_lights'].message_type = traffic__light__pb2._TRAFFICLIGHT
_COMMONROADMAP.fields_by_name['intersections'].message_type = intersection__pb2._INTERSECTION
DESCRIPTOR.message_types_by_name['MapInformation'] = _MAPINFORMATION
DESCRIPTOR.message_types_by_name['CommonRoadMap'] = _COMMONROADMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapInformation = _reflection.GeneratedProtocolMessageType('MapInformation', (_message.Message,), {
  'DESCRIPTOR' : _MAPINFORMATION,
  '__module__' : 'map.commonroad_map_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_map.MapInformation)
  })
_sym_db.RegisterMessage(MapInformation)

CommonRoadMap = _reflection.GeneratedProtocolMessageType('CommonRoadMap', (_message.Message,), {
  'DESCRIPTOR' : _COMMONROADMAP,
  '__module__' : 'map.commonroad_map_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_map.CommonRoadMap)
  })
_sym_db.RegisterMessage(CommonRoadMap)


# @@protoc_insertion_point(module_scope)
