# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commonroad.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commonroad.scenario_definition.protobuf_format.generated_scripts.util_pb2 as util__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.scenario_tags_pb2 as scenario__tags__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.location_pb2 as location__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.lanelet_pb2 as lanelet__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.traffic_sign_pb2 as traffic__sign__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.traffic_light_pb2 as traffic__light__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.intersection_pb2 as intersection__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.static_obstacle_pb2 as static__obstacle__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.dynamic_obstacle_pb2 as dynamic__obstacle__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.environment_obstacle_pb2 as environment__obstacle__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.phantom_obstacle_pb2 as phantom__obstacle__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.planning_problem_pb2 as planning__problem__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ommonroad.proto\x12\ncommonroad\x1a\nutil.proto\x1a\x13scenario_tags.proto\x1a\x0elocation.proto\x1a\rlanelet.proto\x1a\x12traffic_sign.proto\x1a\x13traffic_light.proto\x1a\x12intersection.proto\x1a\x15static_obstacle.proto\x1a\x16\x64ynamic_obstacle.proto\x1a\x1a\x65nvironment_obstacle.proto\x1a\x16phantom_obstacle.proto\x1a\x16planning_problem.proto\"\xba\x01\n\x13ScenarioInformation\x12\x1b\n\x13\x63ommon_road_version\x18\x01 \x02(\t\x12\x14\n\x0c\x62\x65nchmark_id\x18\x02 \x02(\t\x12#\n\x04\x64\x61te\x18\x03 \x02(\x0b\x32\x15.commonroad.TimeStamp\x12\x0e\n\x06\x61uthor\x18\x04 \x02(\t\x12\x13\n\x0b\x61\x66\x66iliation\x18\x05 \x02(\t\x12\x0e\n\x06source\x18\x06 \x02(\t\x12\x16\n\x0etime_step_size\x18\x07 \x02(\x01\"\xf3\x04\n\nCommonRoad\x12\x34\n\x0binformation\x18\x01 \x02(\x0b\x32\x1f.commonroad.ScenarioInformation\x12/\n\rscenario_tags\x18\x02 \x02(\x0b\x32\x18.commonroad.ScenarioTags\x12&\n\x08location\x18\x03 \x02(\x0b\x32\x14.commonroad.Location\x12%\n\x08lanelets\x18\x04 \x03(\x0b\x32\x13.commonroad.Lanelet\x12.\n\rtraffic_signs\x18\x05 \x03(\x0b\x32\x17.commonroad.TrafficSign\x12\x30\n\x0etraffic_lights\x18\x06 \x03(\x0b\x32\x18.commonroad.TrafficLight\x12/\n\rintersections\x18\x07 \x03(\x0b\x32\x18.commonroad.Intersection\x12\x34\n\x10static_obstacles\x18\x08 \x03(\x0b\x32\x1a.commonroad.StaticObstacle\x12\x36\n\x11\x64ynamic_obstacles\x18\t \x03(\x0b\x32\x1b.commonroad.DynamicObstacle\x12>\n\x15\x65nvironment_obstacles\x18\n \x03(\x0b\x32\x1f.commonroad.EnvironmentObstacle\x12\x36\n\x11phantom_obstacles\x18\x0b \x03(\x0b\x32\x1b.commonroad.PhantomObstacle\x12\x36\n\x11planning_problems\x18\x0c \x03(\x0b\x32\x1b.commonroad.PlanningProblem')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commonroad_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCENARIOINFORMATION._serialized_start=281
  _SCENARIOINFORMATION._serialized_end=467
  _COMMONROAD._serialized_start=470
  _COMMONROAD._serialized_end=1097
# @@protoc_insertion_point(module_scope)
