# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynamic_obstacle.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commonroad.scenario_definition.protobuf_format.generated_scripts.obstacle_pb2 as obstacle__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.util_pb2 as util__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dynamic_obstacle.proto',
  package='commonroad',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x64ynamic_obstacle.proto\x12\ncommonroad\x1a\x0eobstacle.proto\x1a\nutil.proto\"\xb4\x03\n\x0f\x44ynamicObstacle\x12\x1b\n\x13\x64ynamic_obstacle_id\x18\x01 \x02(\r\x12@\n\robstacle_type\x18\x02 \x02(\x0e\x32).commonroad.ObstacleTypeEnum.ObstacleType\x12 \n\x05shape\x18\x03 \x02(\x0b\x32\x11.commonroad.Shape\x12(\n\rinitial_state\x18\x04 \x02(\x0b\x32\x11.commonroad.State\x12\x41\n\x15trajectory_prediction\x18\x05 \x01(\x0b\x32 .commonroad.TrajectoryPredictionH\x00\x12>\n\x14set_based_prediction\x18\x06 \x01(\x0b\x32\x1e.commonroad.SetBasedPredictionH\x00\x12\x35\n\x14initial_signal_state\x18\x07 \x01(\x0b\x32\x17.commonroad.SignalState\x12.\n\rsignal_series\x18\x08 \x03(\x0b\x32\x17.commonroad.SignalStateB\x0c\n\nprediction'
  ,
  dependencies=[obstacle__pb2.DESCRIPTOR,util__pb2.DESCRIPTOR,])




_DYNAMICOBSTACLE = _descriptor.Descriptor(
  name='DynamicObstacle',
  full_name='commonroad.DynamicObstacle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dynamic_obstacle_id', full_name='commonroad.DynamicObstacle.dynamic_obstacle_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='obstacle_type', full_name='commonroad.DynamicObstacle.obstacle_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape', full_name='commonroad.DynamicObstacle.shape', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initial_state', full_name='commonroad.DynamicObstacle.initial_state', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trajectory_prediction', full_name='commonroad.DynamicObstacle.trajectory_prediction', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_based_prediction', full_name='commonroad.DynamicObstacle.set_based_prediction', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initial_signal_state', full_name='commonroad.DynamicObstacle.initial_signal_state', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signal_series', full_name='commonroad.DynamicObstacle.signal_series', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='prediction', full_name='commonroad.DynamicObstacle.prediction',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=67,
  serialized_end=503,
)

_DYNAMICOBSTACLE.fields_by_name['obstacle_type'].enum_type = obstacle__pb2._OBSTACLETYPEENUM_OBSTACLETYPE
_DYNAMICOBSTACLE.fields_by_name['shape'].message_type = util__pb2._SHAPE
_DYNAMICOBSTACLE.fields_by_name['initial_state'].message_type = obstacle__pb2._STATE
_DYNAMICOBSTACLE.fields_by_name['trajectory_prediction'].message_type = obstacle__pb2._TRAJECTORYPREDICTION
_DYNAMICOBSTACLE.fields_by_name['set_based_prediction'].message_type = obstacle__pb2._SETBASEDPREDICTION
_DYNAMICOBSTACLE.fields_by_name['initial_signal_state'].message_type = obstacle__pb2._SIGNALSTATE
_DYNAMICOBSTACLE.fields_by_name['signal_series'].message_type = obstacle__pb2._SIGNALSTATE
_DYNAMICOBSTACLE.oneofs_by_name['prediction'].fields.append(
  _DYNAMICOBSTACLE.fields_by_name['trajectory_prediction'])
_DYNAMICOBSTACLE.fields_by_name['trajectory_prediction'].containing_oneof = _DYNAMICOBSTACLE.oneofs_by_name['prediction']
_DYNAMICOBSTACLE.oneofs_by_name['prediction'].fields.append(
  _DYNAMICOBSTACLE.fields_by_name['set_based_prediction'])
_DYNAMICOBSTACLE.fields_by_name['set_based_prediction'].containing_oneof = _DYNAMICOBSTACLE.oneofs_by_name['prediction']
DESCRIPTOR.message_types_by_name['DynamicObstacle'] = _DYNAMICOBSTACLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DynamicObstacle = _reflection.GeneratedProtocolMessageType('DynamicObstacle', (_message.Message,), {
  'DESCRIPTOR' : _DYNAMICOBSTACLE,
  '__module__' : 'dynamic_obstacle_pb2'
  # @@protoc_insertion_point(class_scope:commonroad.DynamicObstacle)
  })
_sym_db.RegisterMessage(DynamicObstacle)


# @@protoc_insertion_point(module_scope)
