# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynamic_obstacle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commonroad.scenario_definition.protobuf_format.generated_scripts.obstacle_pb2 as obstacle__pb2
import commonroad.scenario_definition.protobuf_format.generated_scripts.util_pb2 as util__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64ynamic_obstacle.proto\x12\ncommonroad\x1a\x0eobstacle.proto\x1a\nutil.proto\"\xb4\x03\n\x0f\x44ynamicObstacle\x12\x1b\n\x13\x64ynamic_obstacle_id\x18\x01 \x02(\r\x12@\n\robstacle_type\x18\x02 \x02(\x0e\x32).commonroad.ObstacleTypeEnum.ObstacleType\x12 \n\x05shape\x18\x03 \x02(\x0b\x32\x11.commonroad.Shape\x12(\n\rinitial_state\x18\x04 \x02(\x0b\x32\x11.commonroad.State\x12\x41\n\x15trajectory_prediction\x18\x05 \x01(\x0b\x32 .commonroad.TrajectoryPredictionH\x00\x12>\n\x14set_based_prediction\x18\x06 \x01(\x0b\x32\x1e.commonroad.SetBasedPredictionH\x00\x12\x35\n\x14initial_signal_state\x18\x07 \x01(\x0b\x32\x17.commonroad.SignalState\x12.\n\rsignal_series\x18\x08 \x03(\x0b\x32\x17.commonroad.SignalStateB\x0c\n\nprediction')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dynamic_obstacle_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DYNAMICOBSTACLE._serialized_start=67
  _DYNAMICOBSTACLE._serialized_end=503
# @@protoc_insertion_point(module_scope)
