# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intersection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12intersection.proto\x12\ncommonroad\"\x9e\x01\n\x08Incoming\x12\x13\n\x0bincoming_id\x18\x01 \x02(\r\x12\x19\n\x11incoming_lanelets\x18\x02 \x03(\r\x12\x18\n\x10successors_right\x18\x03 \x03(\r\x12\x1b\n\x13successors_straight\x18\x04 \x03(\r\x12\x17\n\x0fsuccessors_left\x18\x05 \x03(\r\x12\x12\n\nis_left_of\x18\x06 \x01(\r\"k\n\x0cIntersection\x12\x17\n\x0fintersection_id\x18\x01 \x02(\r\x12\'\n\tincomings\x18\x02 \x03(\x0b\x32\x14.commonroad.Incoming\x12\x19\n\x11\x63rossing_lanelets\x18\x03 \x03(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intersection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INCOMING._serialized_start=35
  _INCOMING._serialized_end=193
  _INTERSECTION._serialized_start=195
  _INTERSECTION._serialized_end=302
# @@protoc_insertion_point(module_scope)
