# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commonroad.scenario_definition.protobuf_format.generated_scripts.util_pb2 as util__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\ncommonroad\x1a\nutil.proto\"=\n\rTimeOfDayEnum\",\n\tTimeOfDay\x12\t\n\x05NIGHT\x10\x00\x12\x07\n\x03\x44\x41Y\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\"l\n\x0bWeatherEnum\"]\n\x07Weather\x12\t\n\x05SUNNY\x10\x00\x12\x0e\n\nLIGHT_RAIN\x10\x01\x12\r\n\tHEAVY_AIN\x10\x02\x12\x07\n\x03\x46OG\x10\x03\x12\x08\n\x04SNOW\x10\x04\x12\x08\n\x04HAIL\x10\x05\x12\x0b\n\x07UNKNOWN\x10\x06\"l\n\x0fUndergroundEnum\"Y\n\x0bUnderground\x12\x07\n\x03WET\x10\x00\x12\t\n\x05\x43LEAN\x10\x01\x12\t\n\x05\x44IRTY\x10\x02\x12\x0b\n\x07\x44\x41MAGED\x10\x03\x12\x08\n\x04SNOW\x10\x04\x12\x07\n\x03ICE\x10\x05\x12\x0b\n\x07UNKNOWN\x10\x06\"}\n\x11GeoTransformation\x12\x15\n\rgeo_reference\x18\x01 \x01(\t\x12\x15\n\rx_translation\x18\x02 \x01(\x01\x12\x15\n\ry_translation\x18\x03 \x01(\x01\x12\x12\n\nz_rotation\x18\x04 \x01(\x01\x12\x0f\n\x07scaling\x18\x05 \x01(\x01\"\xdc\x01\n\x0b\x45nvironment\x12#\n\x04time\x18\x01 \x01(\x0b\x32\x15.commonroad.TimeStamp\x12\x38\n\x0btime_of_day\x18\x02 \x01(\x0e\x32#.commonroad.TimeOfDayEnum.TimeOfDay\x12\x30\n\x07weather\x18\x03 \x01(\x0e\x32\x1f.commonroad.WeatherEnum.Weather\x12<\n\x0bunderground\x18\x04 \x01(\x0e\x32\'.commonroad.UndergroundEnum.Underground\"\xb5\x01\n\x08Location\x12\x13\n\x0bgeo_name_id\x18\x01 \x02(\x05\x12\x14\n\x0cgps_latitude\x18\x02 \x02(\x01\x12\x15\n\rgps_longitude\x18\x03 \x02(\x01\x12\x39\n\x12geo_transformation\x18\x04 \x01(\x0b\x32\x1d.commonroad.GeoTransformation\x12,\n\x0b\x65nvironment\x18\x05 \x01(\x0b\x32\x17.commonroad.Environment')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEOFDAYENUM._serialized_start=42
  _TIMEOFDAYENUM._serialized_end=103
  _TIMEOFDAYENUM_TIMEOFDAY._serialized_start=59
  _TIMEOFDAYENUM_TIMEOFDAY._serialized_end=103
  _WEATHERENUM._serialized_start=105
  _WEATHERENUM._serialized_end=213
  _WEATHERENUM_WEATHER._serialized_start=120
  _WEATHERENUM_WEATHER._serialized_end=213
  _UNDERGROUNDENUM._serialized_start=215
  _UNDERGROUNDENUM._serialized_end=323
  _UNDERGROUNDENUM_UNDERGROUND._serialized_start=234
  _UNDERGROUNDENUM_UNDERGROUND._serialized_end=323
  _GEOTRANSFORMATION._serialized_start=325
  _GEOTRANSFORMATION._serialized_end=450
  _ENVIRONMENT._serialized_start=453
  _ENVIRONMENT._serialized_end=673
  _LOCATION._serialized_start=676
  _LOCATION._serialized_end=857
# @@protoc_insertion_point(module_scope)
