# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phantom_obstacle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commonroad.scenario_definition.protobuf_format.generated_scripts.obstacle_pb2 as obstacle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16phantom_obstacle.proto\x12\ncommonroad\x1a\x0eobstacle.proto\"Z\n\x0fPhantomObstacle\x12\x13\n\x0bobstacle_id\x18\x01 \x02(\r\x12\x32\n\nprediction\x18\x02 \x01(\x0b\x32\x1e.commonroad.SetBasedPrediction')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'phantom_obstacle_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PHANTOMOBSTACLE._serialized_start=54
  _PHANTOMOBSTACLE._serialized_end=144
# @@protoc_insertion_point(module_scope)
