# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scenario_tags.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13scenario_tags.proto\x12\ncommonroad\"\xdd\x03\n\x07TagEnum\"\xd1\x03\n\x03Tag\x12\x0e\n\nINTERSTATE\x10\x00\x12\t\n\x05URBAN\x10\x01\x12\x0b\n\x07HIGHWAY\x10\x02\x12\x0b\n\x07\x43OMFORT\x10\x03\x12\x0c\n\x08\x43RITICAL\x10\x04\x12\x0b\n\x07\x45VASIVE\x10\x05\x12\n\n\x06\x43UT_IN\x10\x06\x12\x11\n\rILLEGAL_CUTIN\x10\x07\x12\x10\n\x0cINTERSECTION\x10\x08\x12\x0f\n\x0bLANE_CHANGE\x10\t\x12\x12\n\x0eLANE_FOLLOWING\x10\n\x12\x11\n\rMERGING_LANES\x10\x0b\x12\x0e\n\nMULTI_LANE\x10\x0c\x12\x14\n\x10ONCOMING_TRAFFIC\x10\r\x12\x17\n\x13NO_ONCOMING_TRAFFIC\x10\x0e\x12\x12\n\x0ePARALLEL_LANES\x10\x0f\x12\x0e\n\nRACE_TRACK\x10\x10\x12\x0e\n\nROUNDABOUT\x10\x11\x12\t\n\x05RURAL\x10\x12\x12\r\n\tSIMULATED\x10\x13\x12\x0f\n\x0bSINGLE_LANE\x10\x14\x12\r\n\tSLIP_ROAD\x10\x15\x12\x0f\n\x0bSPEED_LIMIT\x10\x16\x12\x0f\n\x0bTRAFFIC_JAM\x10\x17\x12\r\n\tTURN_LEFT\x10\x18\x12\x0e\n\nTURN_RIGHT\x10\x19\x12\x0c\n\x08TWO_LANE\x10\x1a\x12\x15\n\x11\x45MERGENCY_BRAKING\x10\x1b\"5\n\x0cScenarioTags\x12%\n\x04tags\x18\x01 \x03(\x0e\x32\x17.commonroad.TagEnum.Tag')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scenario_tags_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TAGENUM._serialized_start=36
  _TAGENUM._serialized_end=513
  _TAGENUM_TAG._serialized_start=48
  _TAGENUM_TAG._serialized_end=513
  _SCENARIOTAGS._serialized_start=515
  _SCENARIOTAGS._serialized_end=568
# @@protoc_insertion_point(module_scope)
