# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traffic_light.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commonroad.scenario_definition.protobuf_format.generated_scripts.util_pb2 as util__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13traffic_light.proto\x12\ncommonroad\x1a\nutil.proto\"j\n\x15TrafficLightStateEnum\"Q\n\x11TrafficLightState\x12\x07\n\x03RED\x10\x00\x12\x0e\n\nRED_YELLOW\x10\x01\x12\t\n\x05GREEN\x10\x02\x12\n\n\x06YELLOW\x10\x03\x12\x0c\n\x08INACTIVE\x10\x04\"\x97\x01\n\x19TrafficLightDirectionEnum\"z\n\x15TrafficLightDirection\x12\t\n\x05RIGHT\x10\x00\x12\x0c\n\x08STRAIGHT\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\x11\n\rLEFT_STRAIGHT\x10\x03\x12\x12\n\x0eSTRAIGHT_RIGHT\x10\x04\x12\x0e\n\nLEFT_RIGHT\x10\x05\x12\x07\n\x03\x41LL\x10\x06\"d\n\x0c\x43ycleElement\x12\x10\n\x08\x64uration\x18\x01 \x02(\r\x12\x42\n\x05\x63olor\x18\x02 \x02(\x0e\x32\x33.commonroad.TrafficLightStateEnum.TrafficLightState\"\xf4\x01\n\x0cTrafficLight\x12\x18\n\x10traffic_light_id\x18\x01 \x02(\r\x12\x30\n\x0e\x63ycle_elements\x18\x02 \x03(\x0b\x32\x18.commonroad.CycleElement\x12#\n\x08position\x18\x03 \x01(\x0b\x32\x11.commonroad.Point\x12\x13\n\x0btime_offset\x18\x04 \x01(\r\x12N\n\tdirection\x18\x05 \x01(\x0e\x32;.commonroad.TrafficLightDirectionEnum.TrafficLightDirection\x12\x0e\n\x06\x61\x63tive\x18\x06 \x01(\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'traffic_light_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAFFICLIGHTSTATEENUM._serialized_start=47
  _TRAFFICLIGHTSTATEENUM._serialized_end=153
  _TRAFFICLIGHTSTATEENUM_TRAFFICLIGHTSTATE._serialized_start=72
  _TRAFFICLIGHTSTATEENUM_TRAFFICLIGHTSTATE._serialized_end=153
  _TRAFFICLIGHTDIRECTIONENUM._serialized_start=156
  _TRAFFICLIGHTDIRECTIONENUM._serialized_end=307
  _TRAFFICLIGHTDIRECTIONENUM_TRAFFICLIGHTDIRECTION._serialized_start=185
  _TRAFFICLIGHTDIRECTIONENUM_TRAFFICLIGHTDIRECTION._serialized_end=307
  _CYCLEELEMENT._serialized_start=309
  _CYCLEELEMENT._serialized_end=409
  _TRAFFICLIGHT._serialized_start=412
  _TRAFFICLIGHT._serialized_end=656
# @@protoc_insertion_point(module_scope)
