# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commonroad_dynamic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commonroad.common.protobuf.dynamic.environment_pb2 as environment__pb2
import commonroad.common.protobuf.dynamic.traffic_sign_value_pb2 as traffic__sign__value__pb2
import commonroad.common.protobuf.dynamic.traffic_light_cycle_pb2 as traffic__light__cycle__pb2
import commonroad.common.protobuf.dynamic.static_obstacle_pb2 as static__obstacle__pb2
import commonroad.common.protobuf.dynamic.dynamic_obstacle_pb2 as dynamic__obstacle__pb2
import commonroad.common.protobuf.dynamic.phantom_obstacle_pb2 as phantom__obstacle__pb2
import commonroad.common.protobuf.common.scenario_meta_information_pb2 as scenario__meta__information__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='commonroad_dynamic.proto',
  package='commonroad_dynamic',
  syntax='proto2',
  serialized_options=_b('H\003'),
  serialized_pb=_b('\n\x18\x63ommonroad_dynamic.proto\x12\x12\x63ommonroad_dynamic\x1a\x11\x65nvironment.proto\x1a\x18traffic_sign_value.proto\x1a\x19traffic_light_cycle.proto\x1a\x15static_obstacle.proto\x1a\x16\x64ynamic_obstacle.proto\x1a\x16phantom_obstacle.proto\x1a\x1fscenario_meta_information.proto\"\xdb\x03\n\x11\x43ommonRoadDynamic\x12L\n\x18\x64ynamic_meta_information\x18\x01 \x02(\x0b\x32*.commonroad_common.ScenarioMetaInformation\x12\x34\n\x0b\x65nvironment\x18\x02 \x02(\x0b\x32\x1f.commonroad_dynamic.Environment\x12\x42\n\x13traffic_light_cycle\x18\x03 \x03(\x0b\x32%.commonroad_dynamic.TrafficLightCycle\x12@\n\x12traffic_sign_value\x18\x04 \x03(\x0b\x32$.commonroad_dynamic.TrafficSignValue\x12<\n\x10static_obstacles\x18\x05 \x03(\x0b\x32\".commonroad_dynamic.StaticObstacle\x12>\n\x11\x64ynamic_obstacles\x18\x06 \x03(\x0b\x32#.commonroad_dynamic.DynamicObstacle\x12>\n\x11phantom_obstacles\x18\x07 \x03(\x0b\x32#.commonroad_dynamic.PhantomObstacleB\x02H\x03')
  ,
  dependencies=[environment__pb2.DESCRIPTOR,traffic__sign__value__pb2.DESCRIPTOR,traffic__light__cycle__pb2.DESCRIPTOR,static__obstacle__pb2.DESCRIPTOR,dynamic__obstacle__pb2.DESCRIPTOR,phantom__obstacle__pb2.DESCRIPTOR,scenario__meta__information__pb2.DESCRIPTOR,])




_COMMONROADDYNAMIC = _descriptor.Descriptor(
  name='CommonRoadDynamic',
  full_name='commonroad_dynamic.CommonRoadDynamic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dynamic_meta_information', full_name='commonroad_dynamic.CommonRoadDynamic.dynamic_meta_information', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='environment', full_name='commonroad_dynamic.CommonRoadDynamic.environment', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traffic_light_cycle', full_name='commonroad_dynamic.CommonRoadDynamic.traffic_light_cycle', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traffic_sign_value', full_name='commonroad_dynamic.CommonRoadDynamic.traffic_sign_value', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='static_obstacles', full_name='commonroad_dynamic.CommonRoadDynamic.static_obstacles', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dynamic_obstacles', full_name='commonroad_dynamic.CommonRoadDynamic.dynamic_obstacles', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phantom_obstacles', full_name='commonroad_dynamic.CommonRoadDynamic.phantom_obstacles', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=700,
)

_COMMONROADDYNAMIC.fields_by_name['dynamic_meta_information'].message_type = scenario__meta__information__pb2._SCENARIOMETAINFORMATION
_COMMONROADDYNAMIC.fields_by_name['environment'].message_type = environment__pb2._ENVIRONMENT
_COMMONROADDYNAMIC.fields_by_name['traffic_light_cycle'].message_type = traffic__light__cycle__pb2._TRAFFICLIGHTCYCLE
_COMMONROADDYNAMIC.fields_by_name['traffic_sign_value'].message_type = traffic__sign__value__pb2._TRAFFICSIGNVALUE
_COMMONROADDYNAMIC.fields_by_name['static_obstacles'].message_type = static__obstacle__pb2._STATICOBSTACLE
_COMMONROADDYNAMIC.fields_by_name['dynamic_obstacles'].message_type = dynamic__obstacle__pb2._DYNAMICOBSTACLE
_COMMONROADDYNAMIC.fields_by_name['phantom_obstacles'].message_type = phantom__obstacle__pb2._PHANTOMOBSTACLE
DESCRIPTOR.message_types_by_name['CommonRoadDynamic'] = _COMMONROADDYNAMIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonRoadDynamic = _reflection.GeneratedProtocolMessageType('CommonRoadDynamic', (_message.Message,), dict(
  DESCRIPTOR = _COMMONROADDYNAMIC,
  __module__ = 'commonroad_dynamic_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_dynamic.CommonRoadDynamic)
  ))
_sym_db.RegisterMessage(CommonRoadDynamic)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
