# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: environment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commonroad.common.protobuf.common.util_pb2 as util__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='environment.proto',
  package='commonroad_dynamic',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x65nvironment.proto\x12\x12\x63ommonroad_dynamic\x1a\nutil.proto\"f\n\rTimeOfDayEnum\"U\n\tTimeOfDay\x12\t\n\x05NIGHT\x10\x00\x12\n\n\x06SUNSET\x10\x01\x12\r\n\tAFTERNOON\x10\x02\x12\x08\n\x04NOON\x10\x03\x12\x0b\n\x07MORNING\x10\x04\x12\x0b\n\x07UNKNOWN\x10\x05\"\x87\x01\n\x0bWeatherEnum\"x\n\x07Weather\x12\t\n\x05\x43LEAR\x10\x00\x12\x0e\n\nLIGHT_RAIN\x10\x01\x12\x0c\n\x08MID_RAIN\x10\x02\x12\x0e\n\nHEAVY_RAIN\x10\x03\x12\x07\n\x03\x46OG\x10\x04\x12\x08\n\x04SNOW\x10\x05\x12\x08\n\x04HAIL\x10\x06\x12\n\n\x06\x43LOUDY\x10\x07\x12\x0b\n\x07UNKNOWN\x10\x08\"l\n\x0fUndergroundEnum\"Y\n\x0bUnderground\x12\x07\n\x03WET\x10\x00\x12\t\n\x05\x43LEAN\x10\x01\x12\t\n\x05\x44IRTY\x10\x02\x12\x0b\n\x07\x44\x41MAGED\x10\x03\x12\x08\n\x04SNOW\x10\x04\x12\x07\n\x03ICE\x10\x05\x12\x0b\n\x07UNKNOWN\x10\x06\"\xfb\x01\n\x0b\x45nvironment\x12*\n\x04time\x18\x01 \x01(\x0b\x32\x1c.commonroad_common.TimeStamp\x12@\n\x0btime_of_day\x18\x02 \x01(\x0e\x32+.commonroad_dynamic.TimeOfDayEnum.TimeOfDay\x12\x38\n\x07weather\x18\x03 \x01(\x0e\x32\'.commonroad_dynamic.WeatherEnum.Weather\x12\x44\n\x0bunderground\x18\x04 \x01(\x0e\x32/.commonroad_dynamic.UndergroundEnum.Underground')
  ,
  dependencies=[util__pb2.DESCRIPTOR,])



_TIMEOFDAYENUM_TIMEOFDAY = _descriptor.EnumDescriptor(
  name='TimeOfDay',
  full_name='commonroad_dynamic.TimeOfDayEnum.TimeOfDay',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NIGHT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUNSET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AFTERNOON', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOON', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MORNING', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=70,
  serialized_end=155,
)
_sym_db.RegisterEnumDescriptor(_TIMEOFDAYENUM_TIMEOFDAY)

_WEATHERENUM_WEATHER = _descriptor.EnumDescriptor(
  name='Weather',
  full_name='commonroad_dynamic.WeatherEnum.Weather',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLEAR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIGHT_RAIN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MID_RAIN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEAVY_RAIN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FOG', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SNOW', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HAIL', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOUDY', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=173,
  serialized_end=293,
)
_sym_db.RegisterEnumDescriptor(_WEATHERENUM_WEATHER)

_UNDERGROUNDENUM_UNDERGROUND = _descriptor.EnumDescriptor(
  name='Underground',
  full_name='commonroad_dynamic.UndergroundEnum.Underground',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLEAN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIRTY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DAMAGED', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SNOW', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ICE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=314,
  serialized_end=403,
)
_sym_db.RegisterEnumDescriptor(_UNDERGROUNDENUM_UNDERGROUND)


_TIMEOFDAYENUM = _descriptor.Descriptor(
  name='TimeOfDayEnum',
  full_name='commonroad_dynamic.TimeOfDayEnum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TIMEOFDAYENUM_TIMEOFDAY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=155,
)


_WEATHERENUM = _descriptor.Descriptor(
  name='WeatherEnum',
  full_name='commonroad_dynamic.WeatherEnum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WEATHERENUM_WEATHER,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=293,
)


_UNDERGROUNDENUM = _descriptor.Descriptor(
  name='UndergroundEnum',
  full_name='commonroad_dynamic.UndergroundEnum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UNDERGROUNDENUM_UNDERGROUND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=403,
)


_ENVIRONMENT = _descriptor.Descriptor(
  name='Environment',
  full_name='commonroad_dynamic.Environment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='commonroad_dynamic.Environment.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_of_day', full_name='commonroad_dynamic.Environment.time_of_day', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weather', full_name='commonroad_dynamic.Environment.weather', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='underground', full_name='commonroad_dynamic.Environment.underground', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=657,
)

_TIMEOFDAYENUM_TIMEOFDAY.containing_type = _TIMEOFDAYENUM
_WEATHERENUM_WEATHER.containing_type = _WEATHERENUM
_UNDERGROUNDENUM_UNDERGROUND.containing_type = _UNDERGROUNDENUM
_ENVIRONMENT.fields_by_name['time'].message_type = util__pb2._TIMESTAMP
_ENVIRONMENT.fields_by_name['time_of_day'].enum_type = _TIMEOFDAYENUM_TIMEOFDAY
_ENVIRONMENT.fields_by_name['weather'].enum_type = _WEATHERENUM_WEATHER
_ENVIRONMENT.fields_by_name['underground'].enum_type = _UNDERGROUNDENUM_UNDERGROUND
DESCRIPTOR.message_types_by_name['TimeOfDayEnum'] = _TIMEOFDAYENUM
DESCRIPTOR.message_types_by_name['WeatherEnum'] = _WEATHERENUM
DESCRIPTOR.message_types_by_name['UndergroundEnum'] = _UNDERGROUNDENUM
DESCRIPTOR.message_types_by_name['Environment'] = _ENVIRONMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeOfDayEnum = _reflection.GeneratedProtocolMessageType('TimeOfDayEnum', (_message.Message,), dict(
  DESCRIPTOR = _TIMEOFDAYENUM,
  __module__ = 'environment_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_dynamic.TimeOfDayEnum)
  ))
_sym_db.RegisterMessage(TimeOfDayEnum)

WeatherEnum = _reflection.GeneratedProtocolMessageType('WeatherEnum', (_message.Message,), dict(
  DESCRIPTOR = _WEATHERENUM,
  __module__ = 'environment_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_dynamic.WeatherEnum)
  ))
_sym_db.RegisterMessage(WeatherEnum)

UndergroundEnum = _reflection.GeneratedProtocolMessageType('UndergroundEnum', (_message.Message,), dict(
  DESCRIPTOR = _UNDERGROUNDENUM,
  __module__ = 'environment_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_dynamic.UndergroundEnum)
  ))
_sym_db.RegisterMessage(UndergroundEnum)

Environment = _reflection.GeneratedProtocolMessageType('Environment', (_message.Message,), dict(
  DESCRIPTOR = _ENVIRONMENT,
  __module__ = 'environment_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_dynamic.Environment)
  ))
_sym_db.RegisterMessage(Environment)


# @@protoc_insertion_point(module_scope)
