# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: environment_obstacle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commonroad.common.protobuf.common.util_pb2 as util__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='environment_obstacle.proto',
  package='commonroad_map',
  syntax='proto2',
  serialized_options=_b('H\003'),
  serialized_pb=_b('\n\x1a\x65nvironment_obstacle.proto\x12\x0e\x63ommonroad_map\x1a\nutil.proto\"\x84\x01\n\x1b\x45nvironmentObstacleTypeEnum\"e\n\x17\x45nvironmentObstacleType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x42UILDING\x10\x01\x12\x11\n\rROAD_BOUNDARY\x10\x02\x12\n\n\x06PILLAR\x10\x03\x12\x10\n\x0cMEDIAN_STRIP\x10\x04\"\xc4\x01\n\x13\x45nvironmentObstacle\x12\x1f\n\x17\x65nvironment_obstacle_id\x18\x01 \x02(\r\x12Z\n\robstacle_type\x18\x02 \x02(\x0e\x32\x43.commonroad_map.EnvironmentObstacleTypeEnum.EnvironmentObstacleType\x12\x30\n\x0eobstacle_shape\x18\x03 \x02(\x0b\x32\x18.commonroad_common.ShapeB\x02H\x03')
  ,
  dependencies=[util__pb2.DESCRIPTOR,])



_ENVIRONMENTOBSTACLETYPEENUM_ENVIRONMENTOBSTACLETYPE = _descriptor.EnumDescriptor(
  name='EnvironmentObstacleType',
  full_name='commonroad_map.EnvironmentObstacleTypeEnum.EnvironmentObstacleType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUILDING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROAD_BOUNDARY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PILLAR', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MEDIAN_STRIP', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=90,
  serialized_end=191,
)
_sym_db.RegisterEnumDescriptor(_ENVIRONMENTOBSTACLETYPEENUM_ENVIRONMENTOBSTACLETYPE)


_ENVIRONMENTOBSTACLETYPEENUM = _descriptor.Descriptor(
  name='EnvironmentObstacleTypeEnum',
  full_name='commonroad_map.EnvironmentObstacleTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENVIRONMENTOBSTACLETYPEENUM_ENVIRONMENTOBSTACLETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=191,
)


_ENVIRONMENTOBSTACLE = _descriptor.Descriptor(
  name='EnvironmentObstacle',
  full_name='commonroad_map.EnvironmentObstacle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='environment_obstacle_id', full_name='commonroad_map.EnvironmentObstacle.environment_obstacle_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obstacle_type', full_name='commonroad_map.EnvironmentObstacle.obstacle_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obstacle_shape', full_name='commonroad_map.EnvironmentObstacle.obstacle_shape', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=390,
)

_ENVIRONMENTOBSTACLETYPEENUM_ENVIRONMENTOBSTACLETYPE.containing_type = _ENVIRONMENTOBSTACLETYPEENUM
_ENVIRONMENTOBSTACLE.fields_by_name['obstacle_type'].enum_type = _ENVIRONMENTOBSTACLETYPEENUM_ENVIRONMENTOBSTACLETYPE
_ENVIRONMENTOBSTACLE.fields_by_name['obstacle_shape'].message_type = util__pb2._SHAPE
DESCRIPTOR.message_types_by_name['EnvironmentObstacleTypeEnum'] = _ENVIRONMENTOBSTACLETYPEENUM
DESCRIPTOR.message_types_by_name['EnvironmentObstacle'] = _ENVIRONMENTOBSTACLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnvironmentObstacleTypeEnum = _reflection.GeneratedProtocolMessageType('EnvironmentObstacleTypeEnum', (_message.Message,), dict(
  DESCRIPTOR = _ENVIRONMENTOBSTACLETYPEENUM,
  __module__ = 'environment_obstacle_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_map.EnvironmentObstacleTypeEnum)
  ))
_sym_db.RegisterMessage(EnvironmentObstacleTypeEnum)

EnvironmentObstacle = _reflection.GeneratedProtocolMessageType('EnvironmentObstacle', (_message.Message,), dict(
  DESCRIPTOR = _ENVIRONMENTOBSTACLE,
  __module__ = 'environment_obstacle_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_map.EnvironmentObstacle)
  ))
_sym_db.RegisterMessage(EnvironmentObstacle)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
