# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traffic_sign.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import commonroad.common.protobuf.common.util_pb2 as util__pb2
import commonroad.common.protobuf.common.traffic_sign_element_pb2 as traffic__sign__element__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='traffic_sign.proto',
  package='commonroad_map',
  syntax='proto2',
  serialized_options=_b('H\003'),
  serialized_pb=_b('\n\x12traffic_sign.proto\x12\x0e\x63ommonroad_map\x1a\nutil.proto\x1a\x1atraffic_sign_element.proto\"\xa9\x01\n\x0bTrafficSign\x12\x17\n\x0ftraffic_sign_id\x18\x01 \x02(\r\x12\x44\n\x15traffic_sign_elements\x18\x02 \x03(\x0b\x32%.commonroad_common.TrafficSignElement\x12*\n\x08position\x18\x03 \x02(\x0b\x32\x18.commonroad_common.Point\x12\x0f\n\x07virtual\x18\x04 \x01(\x08\x42\x02H\x03')
  ,
  dependencies=[util__pb2.DESCRIPTOR,traffic__sign__element__pb2.DESCRIPTOR,])




_TRAFFICSIGN = _descriptor.Descriptor(
  name='TrafficSign',
  full_name='commonroad_map.TrafficSign',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='traffic_sign_id', full_name='commonroad_map.TrafficSign.traffic_sign_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='traffic_sign_elements', full_name='commonroad_map.TrafficSign.traffic_sign_elements', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='commonroad_map.TrafficSign.position', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='virtual', full_name='commonroad_map.TrafficSign.virtual', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=248,
)

_TRAFFICSIGN.fields_by_name['traffic_sign_elements'].message_type = traffic__sign__element__pb2._TRAFFICSIGNELEMENT
_TRAFFICSIGN.fields_by_name['position'].message_type = util__pb2._POINT
DESCRIPTOR.message_types_by_name['TrafficSign'] = _TRAFFICSIGN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrafficSign = _reflection.GeneratedProtocolMessageType('TrafficSign', (_message.Message,), dict(
  DESCRIPTOR = _TRAFFICSIGN,
  __module__ = 'traffic_sign_pb2'
  # @@protoc_insertion_point(class_scope:commonroad_map.TrafficSign)
  ))
_sym_db.RegisterMessage(TrafficSign)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
