# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynamic_obstacle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import obstacle_pb2 as obstacle__pb2
import util_pb2 as util__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dynamic_obstacle.proto',
  package='commonroad',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x64ynamic_obstacle.proto\x12\ncommonroad\x1a\x0eobstacle.proto\x1a\nutil.proto\"d\n\tOccupancy\x12\x35\n\ttime_step\x18\x01 \x02(\x0b\x32\".commonroad.IntegerExactOrInterval\x12 \n\x05shape\x18\x02 \x02(\x0b\x32\x11.commonroad.Shape\"/\n\nTrajectory\x12!\n\x06states\x18\x01 \x03(\x0b\x32\x11.commonroad.State\":\n\x0cOccupancySet\x12*\n\x0boccupancies\x18\x01 \x03(\x0b\x32\x15.commonroad.Occupancy\"\xd9\x03\n\x0f\x44ynamicObstacle\x12\x1b\n\x13\x64ynamic_obstacle_id\x18\x01 \x02(\r\x12@\n\robstacle_type\x18\x02 \x02(\x0e\x32).commonroad.ObstacleTypeEnum.ObstacleType\x12 \n\x05shape\x18\x03 \x02(\x0b\x32\x11.commonroad.Shape\x12(\n\rinitial_state\x18\x04 \x02(\x0b\x32\x11.commonroad.State\x12,\n\ntrajectory\x18\x05 \x01(\x0b\x32\x16.commonroad.TrajectoryH\x00\x12\x31\n\roccupancy_set\x18\x06 \x01(\x0b\x32\x18.commonroad.OccupancySetH\x00\x12\"\n\x1ainitial_center_lanelet_ids\x18\x07 \x03(\r\x12!\n\x19initial_shape_lanelet_ids\x18\x08 \x03(\r\x12\x35\n\x14initial_signal_state\x18\t \x01(\x0b\x32\x17.commonroad.SignalState\x12.\n\rsignal_series\x18\n \x03(\x0b\x32\x17.commonroad.SignalStateB\x0c\n\nprediction')
  ,
  dependencies=[obstacle__pb2.DESCRIPTOR,util__pb2.DESCRIPTOR,])




_OCCUPANCY = _descriptor.Descriptor(
  name='Occupancy',
  full_name='commonroad.Occupancy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_step', full_name='commonroad.Occupancy.time_step', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='commonroad.Occupancy.shape', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=166,
)


_TRAJECTORY = _descriptor.Descriptor(
  name='Trajectory',
  full_name='commonroad.Trajectory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='states', full_name='commonroad.Trajectory.states', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=215,
)


_OCCUPANCYSET = _descriptor.Descriptor(
  name='OccupancySet',
  full_name='commonroad.OccupancySet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='occupancies', full_name='commonroad.OccupancySet.occupancies', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=275,
)


_DYNAMICOBSTACLE = _descriptor.Descriptor(
  name='DynamicObstacle',
  full_name='commonroad.DynamicObstacle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dynamic_obstacle_id', full_name='commonroad.DynamicObstacle.dynamic_obstacle_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obstacle_type', full_name='commonroad.DynamicObstacle.obstacle_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='commonroad.DynamicObstacle.shape', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initial_state', full_name='commonroad.DynamicObstacle.initial_state', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trajectory', full_name='commonroad.DynamicObstacle.trajectory', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='occupancy_set', full_name='commonroad.DynamicObstacle.occupancy_set', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initial_center_lanelet_ids', full_name='commonroad.DynamicObstacle.initial_center_lanelet_ids', index=6,
      number=7, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initial_shape_lanelet_ids', full_name='commonroad.DynamicObstacle.initial_shape_lanelet_ids', index=7,
      number=8, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initial_signal_state', full_name='commonroad.DynamicObstacle.initial_signal_state', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signal_series', full_name='commonroad.DynamicObstacle.signal_series', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='prediction', full_name='commonroad.DynamicObstacle.prediction',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=278,
  serialized_end=751,
)

_OCCUPANCY.fields_by_name['time_step'].message_type = util__pb2._INTEGEREXACTORINTERVAL
_OCCUPANCY.fields_by_name['shape'].message_type = obstacle__pb2._SHAPE
_TRAJECTORY.fields_by_name['states'].message_type = obstacle__pb2._STATE
_OCCUPANCYSET.fields_by_name['occupancies'].message_type = _OCCUPANCY
_DYNAMICOBSTACLE.fields_by_name['obstacle_type'].enum_type = obstacle__pb2._OBSTACLETYPEENUM_OBSTACLETYPE
_DYNAMICOBSTACLE.fields_by_name['shape'].message_type = obstacle__pb2._SHAPE
_DYNAMICOBSTACLE.fields_by_name['initial_state'].message_type = obstacle__pb2._STATE
_DYNAMICOBSTACLE.fields_by_name['trajectory'].message_type = _TRAJECTORY
_DYNAMICOBSTACLE.fields_by_name['occupancy_set'].message_type = _OCCUPANCYSET
_DYNAMICOBSTACLE.fields_by_name['initial_signal_state'].message_type = obstacle__pb2._SIGNALSTATE
_DYNAMICOBSTACLE.fields_by_name['signal_series'].message_type = obstacle__pb2._SIGNALSTATE
_DYNAMICOBSTACLE.oneofs_by_name['prediction'].fields.append(
  _DYNAMICOBSTACLE.fields_by_name['trajectory'])
_DYNAMICOBSTACLE.fields_by_name['trajectory'].containing_oneof = _DYNAMICOBSTACLE.oneofs_by_name['prediction']
_DYNAMICOBSTACLE.oneofs_by_name['prediction'].fields.append(
  _DYNAMICOBSTACLE.fields_by_name['occupancy_set'])
_DYNAMICOBSTACLE.fields_by_name['occupancy_set'].containing_oneof = _DYNAMICOBSTACLE.oneofs_by_name['prediction']
DESCRIPTOR.message_types_by_name['Occupancy'] = _OCCUPANCY
DESCRIPTOR.message_types_by_name['Trajectory'] = _TRAJECTORY
DESCRIPTOR.message_types_by_name['OccupancySet'] = _OCCUPANCYSET
DESCRIPTOR.message_types_by_name['DynamicObstacle'] = _DYNAMICOBSTACLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Occupancy = _reflection.GeneratedProtocolMessageType('Occupancy', (_message.Message,), dict(
  DESCRIPTOR = _OCCUPANCY,
  __module__ = 'dynamic_obstacle_pb2'
  # @@protoc_insertion_point(class_scope:commonroad.Occupancy)
  ))
_sym_db.RegisterMessage(Occupancy)

Trajectory = _reflection.GeneratedProtocolMessageType('Trajectory', (_message.Message,), dict(
  DESCRIPTOR = _TRAJECTORY,
  __module__ = 'dynamic_obstacle_pb2'
  # @@protoc_insertion_point(class_scope:commonroad.Trajectory)
  ))
_sym_db.RegisterMessage(Trajectory)

OccupancySet = _reflection.GeneratedProtocolMessageType('OccupancySet', (_message.Message,), dict(
  DESCRIPTOR = _OCCUPANCYSET,
  __module__ = 'dynamic_obstacle_pb2'
  # @@protoc_insertion_point(class_scope:commonroad.OccupancySet)
  ))
_sym_db.RegisterMessage(OccupancySet)

DynamicObstacle = _reflection.GeneratedProtocolMessageType('DynamicObstacle', (_message.Message,), dict(
  DESCRIPTOR = _DYNAMICOBSTACLE,
  __module__ = 'dynamic_obstacle_pb2'
  # @@protoc_insertion_point(class_scope:commonroad.DynamicObstacle)
  ))
_sym_db.RegisterMessage(DynamicObstacle)


# @@protoc_insertion_point(module_scope)
